d3.select("#epochs").property("value","1");d3.selection.prototype.moveToFront=function(){return this.each(function(){this.parentNode.appendChild(this)})};d3.selection.prototype.moveToBack=function(){return this.each(function(){var c=this.parentNode.firstChild;c&&this.parentNode.insertBefore(this,c)})};
function updateTrackedDots(c,e){var f=d3.select("#tracked_group").selectAll(".tracked_dot").data(c);f.exit().remove();f.enter().append("circle").attr("class","tracked_dot");1==e?f.transition().duration(transDur).style("blend-mode","multiply").style("fill","black").attr("r",7.5).attr("cx",function(b){return x2(b[curX[0]])}).attr("cy",function(b){return isNaN(b[curY[0]])?1E3:y(b[curY[0]])}).style("stroke","red").style("stroke-width",2).style("fill","black").attr("fill-opacity",.2):f.style("blend-mode",
"multiply").style("fill","black").attr("r",7.5).attr("cx",function(b){return x2(b[curX[0]])}).attr("cy",function(b){return isNaN(b[curY[0]])?1E3:y(b[curY[0]])}).style("stroke","red").style("stroke-width",2).style("fill","black").attr("fill-opacity",.2)}
function updateTable(c){d3.selectAll("tbody").remove();d3.select("#mean").text(c.length);design_data=[];for(ii=0;ii<c.length;ii++){var e=c[ii],f=Object.keys(e).map(function(b){return e[b]});design_data.push(f)}d3.select("#main_table").append("tbody").selectAll("tr").data(design_data).enter().append("tr").selectAll("td").data(function(b){return b}).enter().append("td").text(function(b){return b})}
d3.select("#epochs").on("change",function(){console.log("dropdown change");var c=+this.value;for(ii=0;ii<allObjects.length;ii++)allObjects[ii].MAU=+dataBase[ii+1][2*c+12],allObjects[ii].FPN=+dataBase[ii+1][2*c+13];for(ii=0;ii<brushees.length;ii++)jj=+brushees[ii].ID,brushees[ii].MAU=+dataBase[jj][2*c+12],brushees[ii].FPN=+dataBase[jj][2*c+13];for(ii=0;ii<tracked_dots.length;ii++)jj=+tracked_dots[ii].ID,tracked_dots[ii].MAU=+dataBase[jj][2*c+12],tracked_dots[ii].FPN=+dataBase[jj][2*c+13];new_brushees=
[];for(ii=0;ii<brushees.length;ii++)isNaN(brushees[ii].MAU)||new_brushees.push(brushees[ii]);updateTable(new_brushees);plotUpdate(allObjects,new_brushees,0);updateTrackedDots(tracked_dots,1);parcoords.render()});
function updateEpochData(c,e,f){var b=d3.select("#epochs"),b=null==b[0][0]?1:b[0][0].value;for(ii=0;ii<c.length;ii++)c[ii].MAU=+dataBase[ii+1][2*b+12],c[ii].FPN=+dataBase[ii+1][2*b+13];for(ii=0;ii<e.length;ii++)jj=+e[ii].ID,e[ii].MAU=+dataBase[jj][2*b+12],e[ii].FPN=+dataBase[jj][2*b+13];for(ii=0;ii<f.length;ii++)jj=+f[ii].ID,f[ii].MAU=+dataBase[jj][2*b+12],f[ii].FPN=+dataBase[jj][2*b+13];new_brushees=[];for(ii=0;ii<e.length;ii++)isNaN(e[ii].MAU)||new_brushees.push(e[ii]);updateTable(new_brushees)}
var modulor,dataList=[],mainWidth=800,mainHeight=300,contents,module,iterationValue,parcolor="black",toolhover,mainRad=2,colMin,colMax,color,parcoords,yPicker,xPicker,pickCircle,pickRectangle,curX=["Cost"],curY=["MAU"],curRad,curCol,colorado=d3.scale.category20(),objectivity=[],categories=["MAU"],objectify={},allObjects=[],trends,scatters,xAx,yAx,xAxText,yAxText,transDur=1600,transBack=transDur,fullList=[],unitList=" kg  kg    m/s s  kg kg kg $M  ".split(" "),colorScale=d3.scale.linear().range(["#E47E21",
"#4977B1"]).interpolate(d3.interpolateHsl),margin={top:5,right:25,bottom:40,left:30},width=mainWidth-margin.left-margin.right,height=mainHeight-margin.top-margin.bottom,parseDates=d3.time.format("%m-%d-%H-%M").parse,x=d3.time.scale().range([0,width]),x2=d3.scale.linear().range([0,width]),y=d3.scale.linear().range([height,0]),y2=d3.time.scale().range([height,0]),radScale=d3.scale.linear().range([1,5]),xAxis=d3.svg.axis().scale(x).orient("bottom").ticks(5),xAxis2=d3.svg.axis().scale(x2).orient("bottom").ticks(5),
yAxis=d3.svg.axis().scale(y).orient("left").ticks(5),yAxis2=d3.svg.axis().scale(y2).orient("left").ticks(5),brushedIn,brushedOut,dataBase=[],data2=[],dates=[],dataAll=[],csver,dataBase2=[],svgTrend,titleTool=d3.select("#titler").attr("class","titleBar"),moduleTool=d3.select("#moduleSpacer").attr("class","refreshModule");dataCollectionSatellite(1);function map_range(c,e,f,b,a){return b+(a-b)*(Math.min(f,Math.max(c,e))-e)/(f-e)}
function dataCollectionSatellite(c){console.log("dataCollection");svgTrend=d3.select("#scatterPlot").append("svg").attr("class","therealliang").attr("width",width+margin.left+margin.right).attr("height",height+margin.top+margin.bottom).append("g").attr("transform","translate("+margin.left+","+margin.top+")");d3.text("data/spacetug_vasc_384_cleaned_v4.csv",function(e,f){dataAll=d3.csv.parseRows(f);var b=[];dataAll.forEach(function(a,d){0<d&&0==d%c&&b.push(dataAll[d])});titleTool;b.forEach(function(a,
d){a.design_id=+b[d][0];a.capability=+b[d][1];a.propulsion=+b[d][2];a.fuel_mass=+b[d][3];a.dfc=+b[d][4];a.payload=+b[d][5];a.speed=0==+b[d][6]?"slow":"fast";a.deltav=+b[d][7];a.base_mass=+b[d][8];a.mass_fraction=+b[d][9];a.isp=+b[d][10];a.dry_mass=+b[d][11];a.wet_mass=+b[d][12];a.cost=+b[d][13];a.mau_1_1=+b[d][14];a.fpn_1_1=+b[d][15];a.mau_2_1=+b[d][16];a.fpn_2_1=+b[d][17];a.mau_3_1=+b[d][18];a.fpn_3_1=+b[d][19];a.mau_4_1=+b[d][20];a.fpn_4_1=+b[d][21];a.mau_5_1=+b[d][22];a.fpn_5_1=+b[d][23];a.mau_6_1=
+b[d][24];a.fpn_6_1=+b[d][25];a.mau_7_1=+b[d][26];a.fpn_7_1=+b[d][27];a.mau_8_1=+b[d][28];a.fpn_8_1=+b[d][29];a.mau_1_2=+b[d][30];a.fpn_1_2=+b[d][31];a.mau_2_2=+b[d][32];a.fpn_2_2=+b[d][33];a.mau_3_2=+b[d][34];a.fpn_3_2=+b[d][35];a.mau_4_2=+b[d][36];a.fpn_4_2=+b[d][37];a.mau_5_2=+b[d][38];a.fpn_5_2=+b[d][39];a.mau_6_2=+b[d][40];a.fpn_6_2=+b[d][41];a.mau_7_2=+b[d][42];a.fpn_7_2=+b[d][43];a.mau_8_2=+b[d][44];a.fpn_8_2=+b[d][45];a.capability_name=b[d][46];a.propulsion_name=b[d][47];objectify={ID:a.design_id,
Payload:a.payload,Propulsion:a.propulsion_name,"Fuel Mass":a.fuel_mass,DFC:a.dfc,Capability:a.capability_name,Response:a.speed,DeltaV:a.deltav,Isp:a.isp,"Mass Frac.":a.mass_fraction,"Base Mass":a.base_mass,"Dry Mass":a.dry_mass,"Wet Mass":a.wet_mass,Cost:a.cost,MAU:a.mau_1_1,FPN:a.fpn_1_1};allObjects.push(objectify)});updateTable(allObjects);parcoordRun();plotTrend(allObjects,allObjects,categories)})}var brushees=allObjects,new_brushees=brushees,tracked_dots=[];
function renegotiateRadius(c){function e(c){curRad="repeat"!=curRad?[c]:void 0}$.when(function(c){void 0!=curRad&&curRad[0]==c&&(curRad="repeat")}(c)).done(function(){$.when(e(c)).done(function(){plotUpdate(allObjects,brushees,0)})})}function renegotiateColor(c){function e(c){curCol="repeat"!=curCol?[c]:void 0}$.when(function(c){void 0!=curCol&&curCol[0]==c&&(curCol="repeat")}(c)).done(function(){$.when(e(c)).done(function(){plotUpdate(allObjects,brushees,0)})})}
function renegotiateY(c){$.when(function(c){curY=[c]}(c)).done(function(){plotUpdate(allObjects,brushees,0)})}function renegotiateX(c){$.when(function(c){curX=[c]}(c)).done(function(){plotUpdate(allObjects,brushees,0)})}
function plotTrend(c,e,f,b){console.log("plotTrend");x.domain(d3.extent(c,function(a){return a.inclination}));y.domain(d3.extent(c,function(a){return a.inclination}));xAx=svgTrend.append("g").attr("class","x axis").attr("transform","translate(0,"+height+")").call(xAxis);xAxText=xAx.append("text").attr("transform","translate("+width+",-20)").attr("y",6).attr("dy",".71em").style("text-anchor","end").text(curX[0]);yAx=svgTrend.append("g").attr("class","y axis").call(yAxis);yAxText=yAx.append("text").attr("transform",
"rotate(-90)").attr("y",6).attr("dy",".71em").style("text-anchor","end").text(curY[0]);scatters=svgTrend.append("g").attr("class","sofresh");scatters.append("g").attr("id","tracked_group");scattered=scatters.append("g").attr("id","dots").selectAll(".dot").data(e).enter().append("circle").attr("class","dot");scattered.attr("r",2).attr("cx",function(a){return"Date"==curX?x(a[curX[0]]):x2(a[curX[0]])}).attr("cy",function(a){return y(a[curY[0]])});tooltipper()}
function plotScrub(c,e,f,b){console.log("plotScrub");$.when(function(){void 0!=scatters&&(scatters.remove(),scattered.remove())}()).done(function(){scatters=svgTrend.append("g").attr("class","sofresh");scattered=scatters.append("g").selectAll(".dot").data(e).enter().append("circle").attr("class","dot");scattered.attr("r",mainRad).attr("cx",function(a){return"Date"==curX?x(a[curX[0]]):x2(a[curX[0]])}).attr("cy",function(a){return y(a[curY[0]])})});tooltipper(mainRad)}
function tooltipper(c){console.log("tooltipper");var e={},f=d3.time.format("%B %e"),b=d3.select("body").append("div").attr("class","tooltip").style("opacity",0);scattered.on("click",function(a){a=[];for(ii=0;ii<tracked_dots.length;ii++)a.push(+tracked_dots[ii].ID);a.includes(+this.id)?(a=a.indexOf(+this.id),tracked_dots.splice(a,1)):tracked_dots.push(allObjects[+this.id-1]);updateEpochData(allObjects,brushees,tracked_dots);updateTrackedDots(tracked_dots,0)}).on("mouseover",function(a){fullList=[];
e={};scattered.transition().duration(200).style("stroke",function(d){return d==a?"black":"none"}).style("stroke-width",function(d){return d==a?5:0});b.transition().duration(200).style("opacity",.85);for(var d,c,k,l,h=parcoords.dimensions(),g=0;g<parcoords.dimensions().length;g++)fullList.push(a[parcoords.dimensions()[g]]),h[g]==curX[0]&&(d=g),h[g]==curY[0]&&(c=g),void 0!=curRad&&h[g]==curRad[0]&&(k=g),void 0!=curCol&&h[g]==curCol[0]&&(l=g);for(g=0;g<fullList.length;g++){var h=parcoords.dimensions()[g],
p=a[parcoords.dimensions()[g]];e[h]=p}parcoords.highlight([e]);parcoords.render();d3.selectAll(".axisValue").text(function(d,a){return 1E3==a?(console.log(fullList[a]),f(fullList[a])+" "+unitList[a]):fullList[a]+" "+unitList[a]});d="Date"==curX[0]?f(a[curX[0]]):a[curX[0]]+" "+unitList[d];c="Date"==curY[0]?f(a[curY[0]]):a[curY[0]]+" "+unitList[c];if(void 0!=curRad)var m="Date"==curRad[0]?f(a[curRad[0]]):a[curRad[0]]+" "+unitList[k];if(void 0!=curCol)var n="Date"==curCol[0]?f(a[curCol[0]]):a[curCol[0]]+
" "+unitList[l];void 0!=curCol&&void 0!=curRad&&b.html(curX[0]+" (X): "+d+"<br/>"+curY[0]+" (Y): "+c+"<br/>"+curRad[0]+" (Radius): "+m+"<br/>"+curCol[0]+" (Color): "+n).style("left",d3.event.pageX+10+"px").style("top",d3.event.pageY-0+"px");void 0!=curCol&&void 0==curRad&&b.html(curX[0]+" (X): "+d+"<br/>"+curY[0]+" (Y): "+c+"<br/>"+curCol[0]+" (Color): "+n).style("left",d3.event.pageX+10+"px").style("top",d3.event.pageY-0+"px");void 0==curCol&&void 0!=curRad&&b.html(curX[0]+" (X): "+d+"<br/>"+curY[0]+
" (Y): "+c+"<br/>"+curRad[0]+" (Radius): "+m).style("left",d3.event.pageX+10+"px").style("top",d3.event.pageY-0+"px");void 0==curCol&&void 0==curRad&&b.html(curX[0]+" (X): "+d+"<br/>"+curY[0]+" (Y): "+c).style("left",d3.event.pageX+10+"px").style("top",d3.event.pageY-0+"px")}).on("mouseout",function(a){d3.selectAll(".axisValue").text("");parcoords.unhighlight([e]);b.transition().duration(500).style("opacity",0);scattered.transition().duration(500).style("stroke-width",0)});plotUpdate(allObjects,brushees,
1)}
function plotUpdate(c,e,f){console.log("plotUpdate");transDur=1==f?0:transBack;$.when(function(){void 0!=scatters&&(void 0!=xAx&&xAx.remove(),void 0!=yAx&&yAx.remove())}()).done(function(){"Date"==curX?(x.domain(d3.extent(c,function(a){return a[curX[0]]})),xAx=svgTrend.append("g").attr("class","x axis").attr("transform","translate(0,"+height+")").call(xAxis)):(x2.domain(d3.extent(c,function(a){return a[curX[0]]})),xAx=svgTrend.append("g").attr("class","x axis").attr("transform","translate(0,"+height+
")").call(xAxis2));xAxText=xAx.append("text").attr("transform","translate("+width+",-20)").attr("y",6).attr("dy",".71em").style("text-anchor","end").text(curX[0]);"Date"==curY?(y2.domain(d3.extent(c,function(a){return a[curY[0]]})),yAx=svgTrend.append("g").attr("class","y axis").call(yAxis2)):(y.domain(d3.extent(c,function(a){return a[curY[0]]})),yAx=svgTrend.append("g").attr("class","y axis").call(yAxis));yAxText=yAx.append("text").attr("transform","rotate(-90)").attr("y",6).attr("dy",".71em").style("text-anchor",
"end").text(curY[0]);if(void 0!=curRad&&"string"==typeof c[0][curRad[0]]){var b=c.map(function(a){return a[curRad[0]]}),b=b.filter(function(a,c){return b.indexOf(a)==c});string_rad_map={};for(var a=0;a<b.length;a++)string_rad_map[b[a]]=a}if(void 0!=curCol&&"string"==typeof c[0][curCol[0]])for(b=c.map(function(a){return a[curCol[0]]}),b=b.filter(function(a,c){return b.indexOf(a)==c}),string_col_map={},a=0;a<b.length;a++)string_col_map[b[a]]=a;void 0!=curRad&&radScale.domain(d3.extent(c,function(a){return"number"==
typeof a[curRad[0]]?a[curRad[0]]:string_rad_map[a[curRad[0]]]}));void 0!=curCol?(colMin=d3.min(c,function(a){return"number"==typeof a[curCol[0]]?a[curCol[0]]:string_col_map[a[curCol[0]]]}),colMax=d3.max(c,function(a){return"number"==typeof a[curCol[0]]?a[curCol[0]]:string_col_map[a[curCol[0]]]}),colorScale.domain([colMin,colMax]),parcolor=function(a){return colorScale("number"==typeof a[curCol[0]]?a[curCol[0]]:string_col_map[a[curCol[0]]])}):parcolor="black";parcoords.color(parcolor);scatters=svgTrend.append("g").attr("class",
"sofresh");scattered.transition().duration(transDur).style("blend-mode","multiply").attr("id",function(a){return a.ID.toString()}).style("fill",function(a){return void 0!=curCol?colorScale("number"==typeof a[curCol[0]]?a[curCol[0]]:string_col_map[a[curCol[0]]]):"black"}).attr("r",function(a){if(void 0!=curRad)return radScale("number"==typeof a[curRad[0]]?a[curRad[0]]:string_rad_map[a[curRad[0]]]);if(void 0==curRad)return mainRad}).attr("cx",function(a){return"Date"==curX?x(a[curX[0]]):x2(a[curX[0]])}).attr("cy",
function(a){return"Date"==curY?y2(a[curY[0]]):isNaN(a[curY[0]])?1E3:y(a[curY[0]])})})}
function parcoordRun(){console.log("parcoorRun");parcoords=d3.parcoords()("#parc").width(mainWidth).height(mainHeight);parcoords.data(allObjects).alpha(.05).lineWidth(.01).color("black").render().shadows().interactive().brushable().reorderable().on("brush",function(c){c=map_range(parcoords.brushed().length,0,500,1,.25);var e=map_range(parcoords.brushed().length,0,500,.35,.15);parcoords.lineWidth(e);parcoords.alpha(c);brushees=parcoords.brushed();plotScrub(allObjects,parcoords.brushed());updateEpochData(allObjects,
brushees,tracked_dots)})}var uploader=document.getElementById("uploader"),reader=new FileReader,loadSeattle=document.getElementById("loadSeattle");reader.onload=function(c){contents=c.target.result;dataCollection(contents,1);uploader.parentNode.removeChild(uploader);loadSeattle.parentNode.removeChild(loadSeattle)};
function handleFiles(){d3.select("#uploader").transition().duration(transDur).style("height","0px");d3.select("#scatterPlot").transition().duration(transDur).style("margin-left","250px");d3.select("#parc").transition().duration(transDur).style("margin-left","250px").style("margin-top","0px");d3.select(".titleBarMain").transition().duration(transDur).style("margin-left","0px");reader.readAsText(this.files[0])}
$.ajax({type:"GET",url:"data/spacetug_vasc_384_cleaned_v4.csv",success:function(c){dataBase=d3.csv.parseRows(c)},error:function(c){console.log("ajax error")},dataType:"text"});